<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>

<!-- Catalogue de la pépinière Plein de Foin -->

<!DOCTYPE Catalogue [
    <!ELEMENT Catalogue (Plant+)>
    <!ELEMENT Plant (noPlant,description,prixUnitaire)>
    <!ELEMENT noPlant (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT prixUnitaire (#PCDATA)>
]>

<Catalogue>
    <Plant>
	<noPlant>10</noPlant>
	<description>Cèdre en boule</description>
	<prixUnitaire>10.99</prixUnitaire>
    </Plant>
    <Plant>
	<noPlant>20</noPlant>
	<description>Sapin</description>
	<prixUnitaire>12.99</prixUnitaire>
    </Plant>
    <Plant>
	<noPlant>40</noPlant>
	<description>Epinette bleue</description>
	<prixUnitaire>25.99</prixUnitaire>
    </Plant>
    <Plant>
	<noPlant>50</noPlant>
	<description>Chêne</description>
	<prixUnitaire>22.99</prixUnitaire>
    </Plant>
    <Plant>
	<noPlant>60</noPlant>
	<description>Erable argenté</description>
	<prixUnitaire>15.99</prixUnitaire>
    </Plant>
    <Plant>
	<noPlant>70</noPlant>
	<description>Erable argenté</description>
	<prixUnitaire>15.99</prixUnitaire>
    </Plant>
    <Plant>
	<noPlant>80</noPlant>
	<description>Herbe à puce</description>
	<prixUnitaire>10.99</prixUnitaire>
    </Plant>
    <Plant>
	<noPlant>81</noPlant>
	<description>Catalpa</description>
	<prixUnitaire>25.99</prixUnitaire>
    </Plant>
    <Plant>
	<noPlant>90</noPlant>
	<description>Pommier</description>
	<prixUnitaire>25.99</prixUnitaire>
    </Plant>
    <Plant>
	<noPlant>95</noPlant>
	<description>Génévrier</description>
	<prixUnitaire>15.99</prixUnitaire>
    </Plant>
</Catalogue>